def build(bld):
	tests = bld.path.ant_glob("test_*.cc")
	for t in tests:
		bld.program(
			features = 'test',
			source = [t],
			target = t.name[:-3],
			includes = '../src ..',
			use = 'zbs',
		)

	from waflib.Tools import waf_unit_test
	bld.add_post_fun(waf_unit_test.summary)
