def build(bld):
	lib_sources = bld.path.ant_glob("**/*.cc")
	bld.shlib(
		source = lib_sources,
		target = 'zbs',
		includes = '.. .',
	)
	bld.install_files(
		'${PREFIX}/include',
		bld.path.ant_glob("zbs/**/*.hh"),
		relative_trick=True
	)
